### ISSUE TITLE
open to modularization?

### ISSUE THREAD

**Issue by mreinstein** [ianharmon/visualizer#1]
hey Ian, 

cool visualizations. :)

I'd like to publish this as a module in npm. Would you be open to a pull request if I modularized this code?

**Comment by ianharmon** [comment]
Thanks, I haven't really worked much with Node packages so I don't know what that would entail, but I'll say probably, I can also throw on a permissive license if you want to make extensive changes

**Comment by mreinstein** [comment]
@ianharmon the changes would be fairly extensive. Here's what I currently would like to change:

* modularize the code
* switch to es6
* produce minified builds
* allow the visualizer to accept more options (`mediaStream`, `canvas`, etc.)
* allow the visualizer to be attached to other things besides the window object (e.g., embedding the visualizations in a div)
* slight performance improvements
* make the visualizations display properly on retina (macbook, ios) screens

**Comment by ianharmon** [comment]
closing with #2
